deviceId: Test
token: ffd_r-fH3fUBHuCjanIy9G9ObGoeLnhnw05Sf87Yx5ANF0Y
credentialSecret: f805939ad14d23f8d464352817554a53287d0d3caa75305fc646d011ecbe5b8b
forgeURL: https://app.flowforge.com
brokerURL: wss://mqtt.flowforge.cloud
brokerUsername: device:dV6vA1pvqx:nq431Brg5d
brokerPassword: ffbd__xvP67-MlKFygXCh5jzR_X_769mSUDPURXV3WUgPdjg
