name: build ctrlX Snaps and package as App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build snap for amd64
        id: amd64-build
        uses: boschrexroth/ctrlx-actions/build-snap@v1
        with: 
            architecture: amd64
      - 
        name: Build snap for arm64
        id: arm64-build
        uses: boschrexroth/ctrlx-actions/build-snap@v1
        with: 
            architecture: arm64
      - 
        name: Package App for ctrlX OS
        id: app-build
        uses: boschrexroth/ctrlx-actions/build-app@v1
        with: 
            path-amd64-snap: ${{steps.amd64-build.outputs.path-snap}}
            path-arm64-snap: ${{steps.arm64-build.outputs.path-snap}}
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0
          files: |
            ${{steps.app-build.outputs.path-app}}
            ${{steps.amd64-build.outputs.path-snap}}
            ${{steps.arm64-build.outputs.path-snap}}
